### PR TITLE
allow false for basePath and add stripPath.

### PR DESCRIPTION
**Pull request by ctalkington**
stripPath is an attempt to standardize how basePath is removed from string. made it a bit more general for other uses.

cc @tkellen

### CODE REVIEW

**Comment by ctalkington** [comment]
ah just noticed something, fixing real quick.

**Comment by ctalkington** [comment]
ok, think we have enough tests and smarter logic now. let me know what you think.

**Comment by ctalkington** [comment]
ah dang, i broke it.

**Comment by tkellen** [comment]
Is this ready to roll now Chris?

**Pull request merged**
